# Generated by Django 5.0.6 on 2024-09-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_userbasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbasket',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
