# Generated by Django 5.0.6 on 2024-09-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_userbasket_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbasket',
            name='product',
        ),
    ]
