# Generated by Django 5.0.6 on 2024-09-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_userbasket_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, default='default-slug', null=True, verbose_name='slug'),
        ),
    ]
