# Generated by Django 5.0.6 on 2024-10-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_blockedips_alter_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='title_az',
            field=models.CharField(max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='title'),
        ),
    ]
