# Generated by Django 5.0.6 on 2024-10-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_tag_title_az_tag_title_en_tag_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_az',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
