# Generated by Django 5.0.6 on 2024-10-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_title_az_product_title_en_product_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small_description_az',
            field=models.CharField(max_length=255, null=True, verbose_name='small_description'),
        ),
        migrations.AddField(
            model_name='product',
            name='small_description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='small_description'),
        ),
        migrations.AddField(
            model_name='product',
            name='small_description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='small_description'),
        ),
    ]
