# Generated by Django 5.0.6 on 2024-10-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_small_description_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_description_az',
            field=models.CharField(max_length=255, null=True, verbose_name='base_description'),
        ),
        migrations.AddField(
            model_name='product',
            name='base_description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='base_description'),
        ),
        migrations.AddField(
            model_name='product',
            name='base_description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='base_description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_az',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
    ]
