# Generated by Django 5.0.6 on 2024-07-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('phone', models.TextField(max_length=200, verbose_name='phone')),
                ('subject', models.TextField(max_length=200, verbose_name='subject')),
                ('massage', models.TextField(max_length=200, verbose_name='massage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OurAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('small_description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
