# Generated by Django 5.0.6 on 2024-09-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurSponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='sponsors_photos/')),
            ],
        ),
    ]
