# Generated by Django 5.0.6 on 2024-10-21 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0009_tag_title_az_tag_title_en_tag_title_ru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='number',
            new_name='final_price',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='product',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
        migrations.AddField(
            model_name='checkout',
            name='basket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.userbasket'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
