# Generated by Django 5.0.6 on 2024-09-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_cultureblock_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultureblock',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
