# Generated by Django 5.0.6 on 2024-10-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogtag_title_az_blogtag_title_en_blogtag_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title_az',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
