# Generated by Django 5.0.6 on 2024-10-22 20:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_title_az_blogpost_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_az',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
